import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { MultiChoice, RegularText, TitleText, ScrollChoice, TextButton } from "widgets.slint";
import { TextStyle, FontSettings, Palette, Sizes } from "styling.slint";

export component SelectChoicePlayScreen inherits Rectangle {
    callback play(info_cat:int, guess_cat:int);
    public function invoke_play() {
        play(info_cat.choice_num, guess_cat.choice_num);
    }
    in property <[string]> info_types: ["Flag", "Outline", "Country", "Capital", "Languages", "Borders", "Region", "Currencies"];
    VerticalLayout {
        padding: Sizes.padding;
        spacing: Sizes.spacing;
        TitleText{
            text: "Choice Play";
        }
        Rectangle {}
        TextButton {
            height: root.height/10;
            width_button: root.width/2;
            text: "Play";
            clicked => {invoke_play()}
        }
        
        Rectangle {}
        TitleText {
            text: "Category displayed";
            style: FontSettings.title-small;
        }
        info_cat := ScrollChoice {
            width: 100%;
            choices: root.info_types;
        }
        TitleText {
            text: "Category to guess";
            style: FontSettings.title-small;
        }
        guess_cat := ScrollChoice {
            width: 100%;
            choices: root.info_types  ;
            choice_num: 2;
        }
        Rectangle {}
    }
}