import { ScrollView, LineEdit, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { ChoiceElem, RegularText, TitleText, HyperLink } from "widgets.slint";
import { FullInfo, TextWithTitle } from "structs.slint";
import { TextStyle, FontSettings, Palette, Sizes } from "styling.slint";

export component HelpScreen inherits Rectangle {
            
    property <[TextWithTitle]> infos : [
        {title:"Flag", text:"mledoze github"},
        {title:"Map", text:"Natural earth & mledoze github"},
        // {title:"Outline", text:""},
        {title:"Population & Area", text:"United Nations - World Population Prospects 2024"},
        // {title:"Area", text:"World Bank indicator"},
        {title:"Everything else", text:"mledoze github"},
    ];
    VerticalLayout {
        padding: Sizes.padding;
        spacing: 0;
        TitleText {  
            text: "Geo Quiz - Help";
        }
        
        scroll := ScrollView {
            VerticalLayout {
                spacing: 0;
                padding-left: Sizes.size_bar; 
                Rectangle {height: 3* Sizes.spacing;}
        RegularText {
            text: "Geo quiz is a quiz app to help you learn more about the world's geography";
            wrap: word-wrap;
        }
        Rectangle {height: 3* Sizes.spacing;}
        TitleText {  
            text: "Sources";
            style: FontSettings.title-small;
        }
        // Rectangle{
        //     background: Math.mod(0,2) == 0 ? Palette.accent1 : Palette.background;
        //     HorizontalBox {
        //         padding: Sizes.padding;
        //         spacing: 0;
        //         RegularText {
        //             width: root.width/5;
        //             text: "Flag";
        //             vertical-alignment: center;
        //             horizontal-alignment: right;
        //             wrap: word-wrap;
        //             style: FontSettings.body-large-bold;
        //         }
        //         RegularText {
        //             vertical-alignment: center;
        //             text: ":";
        //             style: FontSettings.body-large-bold;
        //         }
        //         Rectangle {width: Sizes.spacing;}
        //         HyperLink {
        //             text: "mledoze github";
        //             url: "https://github.com/mledoze/countries";
        //             vertical-alignment: center;
        //             wrap: word-wrap;
        //         }
        //         Rectangle {}
        //     }
        // }
        Rectangle{
            background: Math.mod(0,2) == 0 ? Palette.accent1 : Palette.background;
            HorizontalBox {
                padding: Sizes.padding;
                spacing: 0;
                RegularText {
                    width: root.width/5;
                    text: "Map";
                    vertical-alignment: center;
                    horizontal-alignment: right;
                    wrap: word-wrap;
                    style: FontSettings.body-large-bold;
                }
                RegularText {
                    vertical-alignment: center;
                    text: ":";
                    style: FontSettings.body-large-bold;
                }
                Rectangle {width: Sizes.spacing;}
                HyperLink {
                    text: "Natural earth";
                    url: "https://www.naturalearthdata.com/downloads/10m-cultural-vectors/";
                    vertical-alignment: center;
                    wrap: word-wrap;
                }
                RegularText {
                    vertical-alignment: center;
                    text:" & ";
                }
                HyperLink {
                    text: "mledoze github";
                    url: "https://github.com/mledoze/countries";
                    vertical-alignment: center;
                    wrap: word-wrap;
                }
                Rectangle {}
            }
        }
        Rectangle{
            background: Math.mod(1,2) == 0 ? Palette.accent1 : Palette.background;
            HorizontalBox {
                padding: Sizes.padding;
                spacing: 0;
                RegularText {
                    width: root.width/5;
                    text: "Population & Area";
                    vertical-alignment: center;
                    horizontal-alignment: right;
                    wrap: word-wrap;
                    style: FontSettings.body-large-bold;
                }
                RegularText {
                    vertical-alignment: center;
                    text: ":";
                    style: FontSettings.body-large-bold;
                }
                Rectangle {width: Sizes.spacing;}
                HyperLink {
                    text: "United Nations - World Population Prospects 2024";
                    url: "https://population.un.org/wpp/";
                    vertical-alignment: center;
                    wrap: word-wrap;
                }
                Rectangle {}
            }
        }
        Rectangle{
            background: Math.mod(0,2) == 0 ? Palette.accent1 : Palette.background;
            HorizontalBox {
                padding: Sizes.padding;
                spacing: 0;
                RegularText {
                    width: root.width/5;
                    text: "Everything else";
                    vertical-alignment: center;
                    horizontal-alignment: right;
                    wrap: word-wrap;
                    style: FontSettings.body-large-bold;
                }
                RegularText {
                    vertical-alignment: center;
                    text: ":";
                    style: FontSettings.body-large-bold;
                }
                Rectangle {width: Sizes.spacing;}
                HyperLink {
                    text: "mledoze github";
                    url: "https://github.com/mledoze/countries";
                    vertical-alignment: center;
                    wrap: word-wrap;
                }
                Rectangle {}
            }
        }

        Rectangle {height: Sizes.spacing;}
        HorizontalBox {
            padding: 0;
            spacing: 0;
            RegularText {
                text:"App code is open source: ";
            }
            HyperLink {
                text: "GeoQuiz github";
                url: "https://github.com/guimath/GeoQuiz";
                vertical-alignment: center;
                wrap: word-wrap;
            }
            Rectangle {}
        }
        Rectangle {height: Sizes.spacing;}
        TitleText {  
            text: "Disclaimer";
            style: FontSettings.title-small;
        }
        RegularText {
            text: "The information presented in this app is aggregated from multiple sources. Some details may be missing, simplified, or inaccurate. This app is intended for educational purposes only. For more reliable information, check Wikipedia!";
            // horizontal-alignment: center;
            wrap: word-wrap;
        }
        Rectangle {height: Sizes.spacing;}
        TitleText {  
            text: "Tips";
            style: FontSettings.title-small;
        }
        RegularText {
            text: "Swip action: You can skip a country or go back to the previous one by swiping on the info shown";
            // horizontal-alignment: center;
            wrap: word-wrap;
        }
        Rectangle {height: Sizes.spacing;}
        RegularText {
            text: "Different users: You can select, add & edit users in the scores screen";
            // horizontal-alignment: center;
            wrap: word-wrap;
        }
        Rectangle {}
            }
        }
        HorizontalBox {
            padding: 0;
            spacing: 0;
            Rectangle {}
            RegularText {
                text: "Contact: ";
                horizontal-alignment: center;
            }
            HyperLink {
                text: "guilhem.geoquiz@gmail.com";
                url: "mailto:guilhem.geoquiz@gmail.com";
                vertical-alignment: center;
                wrap: word-wrap;
            }
            Rectangle {}
        }
        Rectangle {height: Sizes.spacing;}
        RegularText {
            text: "Copyright (c) 2025 Guilhem Mathieux";
            horizontal-alignment: center;
            color: Palette.regular_text.darker(0.5);
        }
    }
}
