import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { MultiChoice, RegularText, TitleText, ScrollChoice, TextButton, TextButtonWithIcon, SelectionFilters } from "widgets.slint";
import { TextStyle, FontSettings, Palette, Sizes } from "styling.slint";
import { PlaySelectParams } from "structs.slint";

export component SelectPlayScreen inherits Rectangle {
    callback set_play_config(params : PlaySelectParams);
    in property <[string]> sub_categories_name: ["World", "Africa", "Americas", "Asia", "Europe", "Oceania"];

    VerticalBox {
        padding: Sizes.padding;
        TitleText{
            text: "Play";
        }
        Rectangle {}
        
        RegularText {
            text:"Play order";
            style: FontSettings.title-small;
            horizontal-alignment: center;
        }
        Rectangle {
            background: Palette.highlight1;
            border-radius: Sizes.std_radius;
            VerticalBox {
                padding: Sizes.spacing;
                spacing: Sizes.spacing;
                w_order := MultiChoice {
                    choices: ["Easy first", "Random", "Hard first"];
                    choice_num: 1;
                }

                RegularText {
                    text: w_order.choice_num==0 ? "Start with better known countries (based on scores)" : 
                        w_order.choice_num==1 ? "Random order":
                        "Start with lesser known countries (based on scores)";
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    width: 100%;
                    wrap: word-wrap;
                    style: FontSettings.body-small;
                }
            }
        }
        Rectangle {height: Sizes.spacing;}
        RegularText {
            text:"Filters";
            style: FontSettings.title-small;
            horizontal-alignment: center;
        }
        filter := SelectionFilters {
            sub_categories_name: root.sub_categories_name;
        }
        
        Rectangle {height: Sizes.spacing;}
        TextButtonWithIcon {
            height: root.height/10;
            text: "Free Play";
            clicked => {
                set_play_config(
                    {
                        order: w_order.choice_num, 
                        include_hard: filter.hard, 
                        region_idx: filter.sub_cat, 
                        play_type: true
                    }
                );
            
            }
        }
        TextButtonWithIcon{
            height: root.height/10;
            text: "4 Choices";
            icon: @image-url("img/4choice.svg");
            clicked => {
                set_play_config(
                    {
                        order: w_order.choice_num, 
                        include_hard: filter.hard, 
                        region_idx: filter.sub_cat, 
                        play_type: false
                    }
                );
            }
        }
        Rectangle {}
        Rectangle {}
    }
}