import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { MultiChoice, RegularText, TitleText, ScrollChoice, TextButton, TextButtonWithIcon } from "widgets.slint";
import { TextStyle, FontSettings, Palette, Sizes } from "styling.slint";

export component SelectMainPlayScreen inherits Rectangle {
    callback play(cat_choices:[int], im_choice:int, play_mode:int);
    public function invoke_play() {
        play(
            [cat1.choice_num, cat2.choice_num, cat3.choice_num], 
            cat_im.choice_num,
            w_play_mode.choice_num,
        );
    }
    in property <[string]> info_type_names;
    in property <[string]> guess_type_names;
    in-out property <bool> custom: false;
    property <length> preset_btn_length: (root.width - 2*Sizes.padding - 3*Sizes.spacing)/4;
    VerticalBox {
        padding: Sizes.padding;
        spacing: Sizes.spacing;
        TitleText{
            text: "Free Play";
        }
        Rectangle {}

        Rectangle {
            background: Palette.highlight1;
            border-radius: Sizes.std_radius;
            VerticalBox {
                padding: Sizes.spacing;
                spacing: Sizes.spacing;
                RegularText {
                    text: "Difficulty";
                    style: FontSettings.title-small;
                    horizontal-alignment: center;
                }

                w_play_mode := MultiChoice {
                    choices: ["Learn", "Easy", "Medium", "Hard"];
                    choice_num: 2;
                }
                RegularText {
                    text: w_play_mode.choice_num == 0 ? "All info is shown":
                        w_play_mode.choice_num == 1 ? "All hints are shown": 
                        w_play_mode.choice_num == 2 ? "Hints are available":
                        "No hints";
                    horizontal-alignment: center;
                    style: FontSettings.body-small;
                }
            }
        }
    

        VerticalBox {
            padding: 0;
            spacing: Sizes.spacing;
            TitleText {
                text: "Presets";
                style: FontSettings.title-small;
            }
            HorizontalBox {
                // visible: !root.custom;
                alignment: center;
                spacing: Sizes.spacing;
                padding: 0;
                TextButton {
                    height: Sizes.height_multi_choice;
                    width: root.preset_btn_length;
                    text: "Flags";
                    clicked => {
                        cat_im.set_choice_num(0);
                        cat1.set_choice_num(0);
                        cat2.set_choice_num(1);
                        cat3.set_choice_num(4);
                        if !root.custom {
                            invoke_play()
                        }
                    }
                }

                TextButton {
                    height: Sizes.height_multi_choice;
                    width: root.preset_btn_length;
                    text: "Maps";
                    clicked => {
                        cat_im.set_choice_num(1);
                        cat1.set_choice_num(0);
                        cat2.set_choice_num(2);
                        cat3.set_choice_num(3);
                        if !root.custom {
                            invoke_play()
                        }
                    }
                }
                TextButton {
                    height: Sizes.height_multi_choice;
                    width: root.preset_btn_length;
                    text: "Outlines";
                    clicked => {
                        cat_im.set_choice_num(2);
                        cat1.set_choice_num(7);
                        cat2.set_choice_num(2);
                        cat3.set_choice_num(0);
                        if !root.custom {
                            invoke_play()
                        }
                    }
                }
                TextButton {
                    height: Sizes.height_multi_choice;
                    width: root.preset_btn_length;
                    text: "Country";
                    clicked => {
                        cat_im.set_choice_num(3);
                        cat1.set_choice_num(1);
                        cat2.set_choice_num(5);
                        cat3.set_choice_num(6);
                        if !root.custom {
                            invoke_play()
                        }
                    }
                }
            }
            HorizontalBox {
                padding: 0;
                alignment: center;
                TextButton {
                    height: Sizes.height_multi_choice;
                    width: 2*root.preset_btn_length + Sizes.spacing;
                    text: root.custom?  "Hide custom" : "Custom";
                    clicked => {
                        root.custom = !root.custom;
                    }
                }
            }
            VerticalBox {
                visible: root.custom;
                padding: 0;
                spacing: Sizes.spacing;
                height: root.custom? self.preferred-height: 0px;
                animate height {
                    duration: 500ms;
                    easing: ease-in-out;
                }
                TitleText {
                    text: "Info shown";
                    style: FontSettings.title-small;
                }
                // Rectangle {height: Sizes.spacing;}
                cat_im := ScrollChoice {
                    choices: root.info_type_names;
                    width:  100%;
                }
                TitleText {
                    text: "Info to guess";
                    style: FontSettings.title-small;
                }

                VerticalLayout {
                    padding: 0;
                    // spacing: Sizes.spacing - Sizes.size_bar;
                    cat1 := ScrollChoice {
                        width: 100%;
                        choices: root.guess_type_names;
                    }

                    cat2 := ScrollChoice {
                        width: 100%;
                        choices: root.guess_type_names;
                        choice_num: 1;
                    }

                    cat3 := ScrollChoice {
                        width: 100%;
                        choices: root.guess_type_names;
                        choice_num: 4;
                    }
                }
                TextButtonWithIcon {
                    height: root.height / 10;
                    text: "Play";
                    clicked => {
                        invoke_play()
                    }
                }
            }
        }
        Rectangle {}
    }
}