import { ScrollView, LineEdit, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { ChoiceElem, RegularText, TitleText } from "widgets.slint";
import { FullInfo } from "structs.slint";
import { TextStyle, FontSettings, Palette, Sizes } from "styling.slint";

export component SelectLookUpScreen inherits Rectangle {
    callback search_changed(search: string);
    callback selected(num: int);
    in property <[string]> all: ["Albania", "Argentina", "Australia", "Barbados"];
    in-out property <[bool]> on: [true, true, true, true];
    VerticalLayout {
        padding: Sizes.padding;
        spacing: Sizes.spacing;
        TitleText {  
            text: "Look Up";
        }
        LineEdit {
            placeholder-text: "Search";
            edited(text) => {scroll.viewport-y=0; search_changed(text)}
        }

        scroll := ScrollView {
            VerticalLayout {
                padding-left: Sizes.size_bar; 
                for country[i] in all: VerticalBox{
                    padding: 0;
                    padding-bottom: root.on[i] ? Sizes.spacing/2 : 0;
                    width: 100%;
                    ChoiceElem {
                    radius: 0;
                    text: country;
                    height: root.on[i] ? Sizes.height_look_up : 0;
                    visible: root.on[i];
                    animate height {
                        duration: 300ms;
                        easing: ease-in-out;
                    }
                    clicked => {
                        selected(i);
                    }
                }
            }
            }
        }
    }
}

export component LookUpScreen inherits Rectangle {
    public function reset() {
        scroll.viewport-y = 0;
    }
    in property <FullInfo> infos: {
        name: "Jamaica", 
        text-infos:[
            {title:"Capital", text:"Kingston"},
            {title:"Languages", text:"English, Jamaican Patois"},
            {title:"Region", text:"Caribbean (Americas)"},
            {title:"Borders", text:""},
            {title:"Currencies", text:"Jamaican Dollar (JMD, $)"},
            {title:"Independent", text:"Yes"},
        ], 
        image-infos:[
            {title:"Flag", image:@image-url("../data/flags/jam.svg")},
            {title:"Outline", image:@image-url("../data/outlines/jam.svg")}
        ]};
    
    VerticalLayout {
        padding: 0;
        padding-top: Sizes.padding;
        padding-bottom: Sizes.padding;
        spacing: Sizes.spacing;
        HorizontalBox {
            padding: 0;
            alignment: center;
            Rectangle {width: Sizes.title_height;}
            TitleText {
                text: infos.name;
                wrap: word-wrap;
            }
            Rectangle {width: Sizes.title_height;}
        }
        scroll := ScrollView {
            vertical-scrollbar-policy: always-off;
            VerticalLayout {
                width: scroll.width - Sizes.size_bar;
                padding-left: Sizes.size_bar;
                for image_infos[i] in infos.image-infos: s := VerticalLayout{
                    padding: 0;
                    spacing: 0;
                    width: 100%;
                    Image {
                        width: s.width;
                        height: s.width*(image_infos.image.height/image-infos.image.width);
                        image-fit: contain;
                        source: image_infos.image;
                    }
                    RegularText {
                        text: image_infos.title;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        style: FontSettings.title-small;
                    }
                    
                }
                Rectangle {height: Sizes.spacing;}
                for text_infos[i] in infos.text-infos: Rectangle{
                    background: Math.mod(i,2) == 0 ? Palette.accent1 : Palette.background;
                    HorizontalBox {
                        RegularText {
                            text: "\{text_infos.title}:";
                            vertical-alignment: center;
                            style: FontSettings.title-small;
                        }
                        RegularText {
                            horizontal-stretch: 1;
                            vertical-alignment: center;
                            text: text_infos.text;
                            wrap: word-wrap;
                        }
                    }
                }
                Rectangle {}
            }
        }
    }
}