

export struct TextWithTitle {
    text: string,
    title: string,
}
export struct ImageWithTitle {
    image: image,
    title: string,
}
export struct FullInfo {
    name: string,
    text_infos : [TextWithTitle],
    image_infos : [ImageWithTitle],
}

export enum Screen {
    Start,
    Score,
    SelectLookUp,
    LookUp,
    SelectPlay,
    SelectMainPlay,
    MainPlay,
    SelectChoicePlay,
    ChoicePlay,
}

export enum ChoiceState {
    NotClicked,
    Correct,
    Wrong,
}
export struct TxtOrImg {
    is_txt: bool,
    txt: string,
    img: image,
}

export struct CatInfo {
    category: string,
    full: string,
    first: string,
    with_hint: bool,
}
  

export struct PlaySelectParams {
    order: int,
    include_hard: bool,
    region_idx: int,
    play_type: bool,
}

export struct MainPlayUpdate  {
    num: int,
    out_of: int,
    score: int,
    last_score: int,
    info: TxtOrImg,
    seen: bool, 
}

export struct ChoicePlayUpdate  {
    num: int,
    out_of: int,
    info: TxtOrImg,
    guesses: [TxtOrImg],
    correct_guess: int,
    prev_guess: [bool],
    guess_num: int, 
    default_info: string
}

export struct ScoreStatSlint {
    main_avg: [int],
    main_last: [int],
    choice_avg: [int],
    choice_last: [int],
    main_max:  int,
    choice_max : int,
}

export enum PopupType {
    Add,
    Edit,
    Delete,
    Off,
}