export struct CatInfo {
    category: string,
    full: string,
    first: string,
    with_hint: bool,
}
  
export struct FullUpdate  {
    num: int,
    out_of: int,
    score: int,
    last_score: int,
    flag: image,
    seen: bool, 
}

export struct TextWithTitle {
    text: string,
    title: string,
}
export struct ImageWithTitle {
    image: image,
    title: string,
}
export struct FullInfo {
    name: string,
    text_infos : [TextWithTitle],
    image_infos : [ImageWithTitle],
}

export enum Screen {
    SelectLookUpScreen,
    LookUpScreen,
    Main,
    CutomPlay,
}