

export struct TextWithTitle {
    text: string,
    title: string,
}
export struct ImageWithTitle {
    image: image,
    title: string,
}
export struct FullInfo {
    name: string,
    text_infos : [TextWithTitle],
    image_infos : [ImageWithTitle],
}

export enum Screen {
    Start,
    SelectLookUp,
    LookUp,
    SelectMainPlay,
    MainPlay,
    SelectChoicePlay,
    ChoicePlay,
}

export enum ChoiceState {
    NotClicked,
    Correct,
    Wrong,
}
export struct TxtOrImg {
    is_txt: bool,
    txt: string,
    img: image,
}

export struct CatInfo {
    category: string,
    full: string,
    first: string,
    with_hint: bool,
}
  
export struct MainPlayUpdate  {
    num: int,
    out_of: int,
    score: int,
    last_score: int,
    info: TxtOrImg,
    seen: bool, 
}

export struct ChoicePlayUpdate  {
    num: int,
    out_of: int,
    info: TxtOrImg,
    guesses: [TxtOrImg],
    correct_guess: int,
    prev_guess: [bool],
    guess_num: int, 
}