import { Button, VerticalBox, HorizontalBox, TextEdit, CheckBox, ComboBox, ScrollView} from "std-widgets.slint";
import {CatInfo} from "structs.slint";


component ChoiceElem inherits TouchArea {
    in property <string> text;
    in property <color> background_elem: #ffffff3c;
    public function click() {
        root.clicked();
    } 
    width: 20%;
    height: 30pt;
    Rectangle {
        width: 100%;
        border-radius: 10px;
        background: root.background_elem;
    }
    Text {
        height: 30pt;
        width:100%;
        horizontal-alignment: center;
        vertical-alignment: center;
        wrap: word-wrap;
        text: root.text;
    }
}
export component MultiChoice {
    in property <[string]> choices;
    in property <float> choices_len;
    in property <percent> width_per_elem: 20%;
    in property <length> spacing : 10pt;
    in property <color> background_elem : #ffffff3c;
    in-out property <int> choice_num : 0;
    out property <bool> not_default : root.choice_num != 0;
  
    HorizontalBox {
        padding: 0;
        spacing: root.spacing;
        alignment: center;
        for text[index] in root.choices : ChoiceElem {
            text: text;
            width: width_per_elem;
            background_elem: root.background_elem;
            clicked => {root.choice_num = index}
        }
            
        
    }
    e := Rectangle {
        width: root.width_per_elem;
    }
    highlight := Rectangle{
        x: (root.width - e.width*root.choices_len - root.spacing*(root.choices_len - 1))/2 + (e.width+root.spacing)*root.choice_num;
        background: #ffffff3c;
        height: 30pt;
        width:root.width_per_elem;
        border-radius: 10px;
        animate x {
            duration: 300ms;
            easing: ease-in-out;
        }
    }
}


component ToggleStar inherits TouchArea {
    in property <bool> on;
    property <image> off_img: @image-url("star_off.svg");
    property <image> on_img: @image-url("star_on.svg");
    height: 40px;
    width: 40px;
    im := Image {
        height: 40px;
        width: 40px;
        source: root.off_img;
    }

    public function set_status(on: bool) {
        if on {
            im.source = root.on_img;
        } else {
            im.source = root.off_img;
        }
    }
}

export component ThreeStartScore {
    in property <int> score;
    callback score_changed(score: int);
    VerticalBox {
        padding: 0;
        HorizontalBox {
            padding: 0;

            star1 := ToggleStar {
                clicked => {
                    internal_score_change(1)
                }
            }

            star2 := ToggleStar {
                clicked => {
                    internal_score_change(2)
                }
            }

            star3 := ToggleStar {
                clicked => {
                    internal_score_change(3)
                }
            }
        }
    }
    function internal_score_change(score: int) {
        set_score(score);
        score_changed(score);
    }
    public function set_score(score: int) {
        star1.set_status(score > 0);
        star2.set_status(score > 1);
        star3.set_status(score > 2);
    }
}
export component MainText inherits Text {
    // font-family: 
    font-size: 14pt;
    // color: white;
}

export component HiddenText inherits TouchArea {
    in-out property <string> name;
    in-out property <string> first_letter;
    in-out property <string> type;
    in property <bool> show;
    in-out property <bool> show_first_letter;
    in-out property <length> size_hint: 40pt;
    in property <int> play_mode; 
    callback hint();

    public function update_cat(cat: CatInfo) {
        self.type = cat.category;
        self.name = cat.full;
        self.first_letter = cat.first;

        if root.play_mode == 1 && cat.with_hint { 
            self.size_hint = 40pt;
        }
        else {
            self.size_hint = 0pt;
        }

        if root.play_mode == 2 && cat.with_hint {
            self.show_first_letter = true;
        }
        else {
            self.show_first_letter = false;
        }

    }
    

    VerticalBox {
        padding: 0;
        Rectangle {
            background: #4a4458ff;
            border-radius: 10px;
            preferred-height: 70pt;
            HorizontalLayout {
                padding: 0;
                padding-left: 10px;
                padding-right: 10px;
                w_type := MainText {
                    horizontal-alignment: right;
                    vertical-alignment: center;
                    text: root.type;
                }
                Rectangle {width: 10px;}
                MainText { 
                    horizontal-stretch: 1;
                    vertical-stretch: 1;
                    height: 100%;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    text: show ? root.name: root.first_letter;
                    visible: root.show || root.show_first_letter;
                    wrap: word-wrap;
                }
                
                
            }   
        }
        
    }
    
    TouchArea {
        x : root.width - root.size_hint - 10px;
        height: root.size_hint;
        width: root.size_hint;
        clicked => {
            hint();
            root.size_hint = 0;
            root.show_first_letter = true
        }
        animate height, width {
            duration: 300ms;
            easing: ease-in-out;
        }
    }
    Image {
        x : root.width - root.size_hint  - 10px;
        source: @image-url("hint2.svg");
        height: root.size_hint;
        width: root.size_hint;
        animate height, width, x {
            duration: 400ms;
            easing: ease-in-out;
        }
    }
}

export component ScrollChoice inherits HorizontalLayout {
    in property <[string]> choices: ["Country", "Capital", "Languages", "Borders", "Region", "Currencies"];
    in property <length> width_per_elem: 100px;
    in-out property <int> choice_num:0;
    in property <length> spacing_i: 20px;
    property <length> size_bar: 12px; // bar is showing on modern-black
    function set_x() -> length {
        return - (root.choice_num* (root.width_per_elem+ root.spacing_i));
    }
    alignment: center;
    padding: 0;
    spacing: 0;
    Image {
        source: @image-url("arrow_left.svg");
        height: 30pt;
        width: 6pt;
        colorize: root.choice_num == 0 ? #ffffff55: white;
    }
    Rectangle {
        width: root.size_bar;
    }
    scroll := ScrollView {

        height: 30pt +root.size_bar;
        viewport-height: 30pt;
        horizontal-scrollbar-policy: always-off;
        // viewport-width: (num_choice+1)*width_per_elem;
        width: 3*width_per_elem+ 2*root.spacing_i + root.size_bar;
        viewport-x: set_x();
        HorizontalLayout {
            padding: 0;
            spacing: root.spacing_i;
            Rectangle {width: root.width_per_elem;}
            for text[index] in root.choices : ChoiceElem {
                
                text: text;
                width: width_per_elem;
                background_elem: index==root.choice_num ? #ffffff62 : #ffffff3c;
                // horizontal-alignment: center;
                // vertical-alignment: center;
                clicked => {root.choice_num = index; scroll.viewport-x= set_x();}
            }
            Rectangle {width: width_per_elem;}
        }
        scrolled() => {
            if scroll.viewport-x >= set_x() + root.spacing_i + root.width_per_elem/2 {
                root.choice_num -= 1;
            } 
            else if scroll.viewport-x <= set_x() - root.spacing_i - root.width_per_elem/2 {
                root.choice_num += 1;
            }
        }
        
    }
    Image {
        source: @image-url("arrow_left.svg");
        height: 30pt;
        width: 6pt;
        rotation-angle: -180deg;
        colorize: root.choice_num == 5 ? #ffffff55: white;
    }
}